config/routes.rb
Rails.application.routes.draw do

  resources :payment_details, except: [:show, :destroy, :update,:edit ]

  resources :papers, except: [:destroy, :show ]

  devise_for :users

  get "credits" => "static_pages#credits"
  get "download_doc" => "static_pages#download_doc"
  get "selection" => "static_pages#selection"
  get "sign_in" => "devise/sessions#new"
  get "home" => "static_pages#home"
  get "call_for_papers" => "static_pages#call_for_papers"
  get "important_dates" => "static_pages#important_dates"
  get "paper_ethics" => "static_pages#paper_ethics"
  get "committee" => "static_pages#committee"
  get "venue_and_contact" => "static_pages#venue_and_contact"
  get "download_pdf" => "static_pages#download_pdf"

  root 'static_pages#home'

end

app/models/paper.rb
class Paper < ActiveRecord::Base
	acts_as_xlsx
	belongs_to :user
	scope :featured, -> { where(:featured => true) }
	scope :by_type_of_conference, -> type_of_conference { where(:type_of_conference => type_of_conference) } 
	paginates_per 10
	has_attached_file :paper_version1,
	:storage => :dropbox,
	:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
	:dropbox_visibility => 'public'
	has_attached_file :paper_version2,
	:storage => :dropbox,
	:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
	:dropbox_visibility => 'public'
	# before_post_process :transliterate_file_name
	do_not_validate_attachment_file_type :paper_version1
	do_not_validate_attachment_file_type :paper_version2
	enum type_of_conference: [ "CSE & IT", "ECE", "EEE", "MECH & CIVIL" ] 
	private
		# def transliterate_file_name
		#   extension = Paper.extname(local_file_name).gsub(/^\.+/, '')
		#   filename = local_file_name.gsub(/\.#{extension}$/, '')
  # 		  self.local.instance_write(:file_name, "#{transliterate(filename)}.#{transliterate(extension)}")
  # 		end
end

app/models/payment_detail.rb
class PaymentDetail < ActiveRecord::Base
	acts_as_xlsx
	belongs_to :user
	has_attached_file :dd_copy,
	:storage => :dropbox,
	:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
	:dropbox_visibility => 'public'
  	validates_attachment_content_type :dd_copy, :content_type => /\Aimage\/.*\Z/, :size => { :in => 0..1000.kilobytes }	
  	validates_uniqueness_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # has_attached_file :paper_version1,:paper_version2
  # do_not_validate_attachment_file_type :paper_version1,:paper_version2
  enum designation: [ "Student", "Faculty Member", "Delegates" ]
  has_many :papers
  has_one :payment_detail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

 protected
	def after_sign_in_path_for(resource)
    	selection_path
  	end
	def after_sign_out_path_for(resource)
   		home_path 
  	end
  	def after_sign_up_path_for(resource)
    	selection_path
  	end
    def after_update_path_for(resource)
      papers_path 
    end
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:last_name, :email, :password, :password_confirmation, :first_name, :designation,:college_name,:mobile_number) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end

end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  has_scope :featured, :type => :boolean
  has_scope :by_type_of_conference
  respond_to :html

  def index
    @papers = apply_scopes(Paper).all.page params[:page]
    if current_user.email != "admin@ncrtet2015.com"
      if @papers.find_by_user_id(current_user.id)
        @papers=@papers.where(user_id: current_user.id)
       else
        redirect_to new_paper_path
      end
    else
      respond_to do |format|
        format.html
        format.xlsx
      end 
    end  
  end

  def show
  end

  def new
    @paper = Paper.new
  end

  def edit
  end

  def create
    @paper = Paper.new(paper_params)
    @paper.save
    @paper.user_id = current_user.id
    @paper.save
    if @paper.save
      @paper.paper_number = "C15#{@paper.user_id}-#{@paper.id}"
      @paper.save
      # RegistrationMailer.registration_success(@registration).deliver_now
      # format.html { redirect_to papers_path, notice: 'Paper was successfully Uploaded.' }
      # format.json { render :show, status: :created, location: @paper }
    else
      format.html { render :new }
      format.json { render json: @registration.errors, status: :unprocessable_entity }
    end
    redirect_to papers_path 
  end

  def update
    @paper.update(paper_params)
    redirect_to papers_path 
  end

  def destroy
    @paper.destroy
    respond_with(@paper)
  end

  private
    def set_paper
      @paper = Paper.find(params[:id])
    end

    def paper_params
      params.require(:paper).permit(:type_of_conference, :paper_title, :abstract, :paper_version1, :paper_version2)
    end
end

app/controllers/payment_details_controller.rb
class PaymentDetailsController < ApplicationController
  before_action :set_payment_detail, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 
  respond_to :html

  def index 
    @payment_details = PaymentDetail.all
    if current_user.email != "admin@ncrtet2015.com"
      if @payment_details.find_by_user_id(current_user.id)
        
      else
        redirect_to new_payment_detail_path
      end
    else
      respond_to do |format|
        format.html
        format.xlsx
      end
    end  
  end

  def show
    respond_with(@payment_detail)
  end

  def new
    @payment_detail = PaymentDetail.new

    respond_with(@payment_detail)
  end

  def edit
  end

  def create
    @payment_detail = PaymentDetail.new(payment_detail_params)
    @payment_detail.user_id = current_user.id
    if current_user.designation == "Student"  
      @payment_detail.amount = 600
    elsif current_user.designation == "Faculty Member" 
      @payment_detail.amount = 800
    elsif current_user.designation == "Delegates" 
      @payment_detail.amount = 1000
    end
    @payment_detail.save
    if @payment_detail.save
      @payment_detail.user_number = "C15#{@payment_detail.id}"
      @payment_detail.save
      # RegistrationMailer.registration_success(@registration).deliver_now
      # format.html { redirect_to papers_path, notice: 'Paper was successfully Uploaded.' }
      # format.json { render :show, status: :created, location: @paper }
    else
      # flash[:notice] = "Post successfully created"
    end
    redirect_to payment_details_path   
  end

  def update
    @payment_detail.update(payment_detail_params)
    respond_with(@payment_detail)
  end

  def destroy
    @payment_detail.destroy
    respond_with(@payment_detail)
  end

  private
    def set_payment_detail
      @payment_detail = PaymentDetail.find(params[:id])
    end

    def payment_detail_params
      params.require(:payment_detail).permit(:amount, :dd_number, :bank, :branch,:dd_copy)
    end
end

app/controllers/static_pages_controller.rb
  class StaticPagesController < ApplicationController
  def home
  end

  def call_for_papers
  end

  def important_dates
  end

  def paper_ethics
  end

  def committee
  end

  def venue_and_contact
  end
  def selection
  end
  def credits
  end
  def download_doc
  send_file(
    "#{Rails.root}/public/ieee_format.doc",
    filename: "ieee_format.doc",
    type: "application/doc"
  )
  end
  def download_pdf
  send_file(
    "#{Rails.root}/public/images.pdf",
    filename: "brouchure.pdf",
    type: "application/pdf"
  )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/payment_details_helper.rb
module PaymentDetailsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang=''>
<head> 
  <script src="menu.js"></script>
  <meta charset='utf-8'>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="menu.css">
   <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
   

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
   
   <title>National Conference on Recent Trends In Engineering and Technology 15' | St. Joseph's Institute of Technology</title>
</head>
<body>
<% if user_signed_in? %>
	<p align="right" font-size="40px">Hi! ,<%= current_user.first_name %>&nbsp;&nbsp;&nbsp;</p>
<%end%> <center>
<table style="padding:20px">
		<tr>
		<td style="background-color:white;width:150px"><%= link_to image_tag("sjit.png",alt: "SJIT", size:"130x155"), "http://stjosephstechnology.ac.in" %></td>
		<td style="background-color:white">
			<p >
				<h2 align="center"> St. Joseph's Institute of Technology</h2></center><h3>
				<small><center>OMR, Chennai-119.</center></small></h3>  </p>
				<p><h3 align="center"><center>2<sup>nd</sup> National Conference<br> on<br> Recent Trends in Engineering and Technology </h3>
				</p>	</td> 
		<td style="background-color:white">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to image_tag("Untitled.png"),home_path %></td>
		</tr>
		</table></center>
	<br>
<div id='cssmenu'>
<ul>
                <li><%= link_to "Home",home_path %></li>
				<li><%= link_to "Info Log", call_for_papers_path %></li>
                <li><%= link_to "Important Dates", important_dates_path %></li>
               <!-- <li><%= link_to "Paper Ethics", paper_ethics_path %></li> -->
                <li><%= link_to "Committee", committee_path %></li>	
                <li><%= link_to "Venue and Contact", venue_and_contact_path %></li>
               
                <% if user_signed_in? %>
	                <% if current_user.email != "admin@ncrtet2015.com" %>	
	                	<li><%= link_to "Upload your paper", papers_path %></li>
	                	<li><%= link_to "Event Registration", payment_details_path %></li>
						<li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
					<% else %>
						<li><%= link_to "Download paper list", papers_path %></li>
						<li><%= link_to "Download payment details", payment_details_path %></li>
						<li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
					<% end %>
				<% else %>
					<li><%= link_to "Log in/Register", new_user_session_path %></li>
					
				<% end %>
								
							</ul>
</div>

		<%= yield %>
		<div class="col-md-12">
<footer><br>
<div style="color: #FFF;padding:5px;height:20px;text-align:right">
<object align="left">Crafted with &hearts; by <%= link_to "Web Crew",credits_path %></object>
Copyright &copy; <a href="http://www.stjosephstechnology.ac.in/">St.joseph's Institute Of Technology</a>
</div>
	
<!-- </font> -->
</footer><!-- End footer -->
</div>
</body>
<html>

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_of_conference %><br>
    <%= f.select :type_of_conference, options_for_select(Paper.type_of_conferences.map{|x| [x[0], x[0]]}),:size=> 30 %>  </div>
  <div class="field">
    <%= f.label :paper_title %><br>
    <%= f.text_field :paper_title,size:50 %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br>
    <%= f.text_area :abstract,size:'50x10' %>
  </div>
  <div class="field">
    <%= f.label "Full Paper" %><br>
    <%= f.file_field :paper_version1 %>
  </div>
  <div class="actions">
    <%= f.submit  "Upload Paper"%>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Add Paper Version 2</h1>
<%= form_for(@paper) do |f| %>
	<div class="field">
    	<%= f.label :paper_version2 %><br>
    	<%= f.file_field :paper_version2 %>
	</div>
	<div class="actions">
    	<%= f.submit %>
	</div>
<% end %>
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<% if current_user.email != "admin@ncrtet2015.com" %>
<p id="notice"><%= notice %></p>
<h1>Uploaded Papers</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Paper Number</th>
        <th>Type of conference</th>
        <th>Paper title</th>
        <th>Full Paper</th>
        <th>Edited Paper</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @papers.each do |paper| %>
      <% if current_user.id == paper.user_id %>
        <tr>
          <td><%= paper.paper_number %></td>
          <td><%= paper.type_of_conference %></td>
          <td><%= paper.paper_title %></td> 
          <td><%= link_to "#{paper.paper_version1_file_name}", paper.paper_version1.url(download: true) %></td>
          <td>
            <% if paper.paper_version2_file_size != nil %>
              <%= link_to "#{paper.paper_version2_file_name}", paper.paper_version2.url(download: true) %>
            <% else %>
               NA
            <% end %>
          </td>
          <td>
            <% if paper.paper_version2_file_size == nil %>    
               <%= link_to 'Add Paper V2', edit_paper_path(paper) %>
            <% else %>
                <%= link_to 'Modify Paper V2', edit_paper_path(paper) %>
            <% end %>
            <% end %>
        </td>
      </tr>
    <% end %>
</tbody>
</table>
<br>
<center><%= paginate @papers %></center>
<%= link_to 'New Paper', new_paper_path, id: "col" %><br>


<% else %>
  <h1>Uploaded Papers</h1>
  <%= link_to "Export",papers_path(format: "xlsx") %>
  <%= form_tag("/papers", method: "get", by_type_of_conference: 1) do %>
  <%= label_tag(:q, "Type of Conference") %>
  <%= select_tag "by_type_of_conference", "<option value=0>CSE & IT</option><option value=1>ECE</option><option value=2>EEE</option><option value=3>MECH & CIVIL</option>".html_safe %>
  <%= submit_tag("FILTER") %>
<% end %>
  
  <%# link_to "Ruby on Rails search", controller: "papers", xby_type_of_conference: 1 %>
    
  <table class="table">
    <thead>
      <tr>
        <th>Paper Number</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>E-mail Id</th>
        <th>College Name</th>
        <th>Mobile Number</th>
        <th>Designation</th>
        <th>Type of conference</th>
        <th>Paper title</th>
        <th>Full Paper</th>
        <th>Edited Paper</th>
      </tr>
    </thead>
    <tbody>
        <% @papers.each do |paper| %>
        <tr>
          <td><%= paper.paper_number %></td>
          <td><%= paper.user.first_name %></td>
          <td><%= paper.user.last_name %></td>
          <td><%= paper.user.email %></td>
          <td><%= paper.user.college_name %></td>
          <td><%= paper.user.mobile_number %></td>
          <td><%= paper.user.designation %></td>
          <td><%= paper.type_of_conference %></td>
          <td><%= paper.paper_title %></td> 
          <td><%= link_to "#{paper.paper_version1_file_name}" ,paper.paper_version1.url(download: true) %></td>
          <td>
            <% if paper.paper_version2_file_size != nil %>
              <%= link_to "#{paper.paper_version2_file_name}", paper.paper_version2.url(download: true) %>
            <% else %>
               NA
            <% end %>
          </td>
          <% end %>
     </tr>
     </tbody>
     </table> 
     <center><%= paginate @papers %></center>
<% end %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type of conference:</strong>
  <%= @paper.type_of_conference %>
</p>

<p>
  <strong>Paper title:</strong>
  <%= @paper.paper_title %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @paper.abstract %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>

app/views/payment_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @payment_detail.amount %>
</p>

<p>
  <strong>Dd number:</strong>
  <%= @payment_detail.dd_number %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @payment_detail.bank %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @payment_detail.branch %>
</p>

<%= link_to 'Edit', edit_payment_detail_path(@payment_detail) %> |
<%= link_to 'Back', payment_details_path %>

app/views/static_pages/call_for_papers.html.erb
<br>
<div class="col-md-8">
<div class="row" >
<section class="topspace topspace-40 whiteshadow ">
<div class="span14" style="background-color:white;color:#333;">
<div class="inner " style="background-color:white;color:#333;" >
<!--general instructions-->
<h2><span>Information Log</span></h2>
			<div class="heading_border"></div>

<!-- submission instructions-->
<h3>SUBMISSION OF PAPERS</h3>
<div>
<ul type="square" style="line-height:20px;font-size:14px;background-color:white">
<li>1. Authors are required to submit their papers (maximum of 8 A4 sized pages) adhering to the IEEE specified format (a copy of which is available for download in the site).</li>
<li>2. Authors must upload their papers onto the conference website.</li>
<li>3. The submitted papers must be original and unpublished.</li>
<li>4. Double blind peer reviews will be followed.</li>
<li>5. Registrations must be done online and a scanned copy of the Demand Draft must be enclosed with it.</li>
<li>6. The DD must be drawn in favour of "St.Joseph's Institute of Technology", payable within Chennai at any nationalised bank.</li>
<li>7. Selected papers will be pubished in the International Journal of Advances in Engineering, Research (IJAER).</li>
</ul>
</div>
<!-- Service text-->
<div >
<h3>REGISTRATION</h3>
	<ul style="line-height:20px;font-size:14px;background-color:white;color:black;">
		<li>1. Authors must register online at the conference website.</li>
		<li>2. A valid phone number and email ID must be given, along with a password of minimum 8 characters.</li>
		<li>3. Authors must register on or before 27th march 2015.</li>
	</ul>
<h3>EVENT REGISTRATION</h3>
 	<ul style="line-height:20px;font-size:14px;background-color:white;color:black;">
		<li>1. The Demand Draft for the required amount must be drawn.</li>
 		<li>2. The DD number must be entered along with the name of the bank and branch.</li>
		<li>3. The scanned copy of the DD must be uploaded.</li>
	</ul>
	<h3>
	Payment Detials
</h3>
	<table style="width:400px;">
<tr>
	<th style="border:1px solid #151515">
		Type of person
	</th>
	<th style="border:1px solid #151515">
		Amount to be paid
	</th>
</tr>
<tr>
	<td style="border:1px solid #151515">
		Students
	</td>
	<td style="border:1px solid #151515">
		Rs. 600 
	</td>
</tr>
<tr>
	<td style="border:1px solid #151515">
		Faculty
	</td>
	<td style="border:1px solid #151515">
		Rs. 800
	</td>
</tr>
<tr>
	<td style="border:1px solid #151515">
		Delegates
	</td>
	<td style="border:1px solid #151515">
		Rs. 1000
	</td>
</tr>
</table>
<h3>UPLOAD YOUR PAPER</h3>
	<ul style="line-height:20px;font-size:14px;background-color:white;color:black;">
		<li>1. Select the paper type and enter the Title and Abstract.</li>
		<li>2. Upload your full paper.</li>
		<li>3. If necessary, the paper can be edited and uploaded again.</li>
	</ul>
	
</div>
<!-- /inner -->
</div> <!-- /span8 -->
</div>

<br>
<br>
<h3 style="background-color:white; color:red;text-align:center">Topics of interest for submission include, but are not limited to: </h3>
</div>	 	
<div class="clearfix"></div>
<br>
<div class="span14" style="background-color:white;color:#333;">
<div class="inner untop" >
<table align="center" style="font-size:14px; margin-left:45px; color:black;width:700px" >
<tr>
<td>
<h3 style="margin-left:40px; color:#333;font-size:28px">CSE & IT:</h3><br>
<p style="margin-left:40px; color:black;font-size:14px;line-height:20px" >
Cloud Computing<br>
Grid computing<br>
Big data<br>
Mobile computing <br>
Computer & network security<br>
Data/Text mining<br>
Internet information systems & technologies<br>
Semantic web & web services<br>
Cluster Computing <br>
Open Source technology<br>
Cyber Crime and Security <br>
AI & Expert System </p>
</td>
<td>
<font style="margin-left:300;font-size:14px"><b>Contact Number:<br> Dr. J. Dafni Rose - 9840009246
<br> Dr. S. Kalarani - 9840009250</font></b>
</td>
</tr>
<tr>
<td>
<h3 style="font-size:28px;margin-left:40px; color:#333">ECE:</h3><br>
<p style="font-size:14px;margin-left:40px; color:black;line-height:20px" >Coding Theory & Cognitive Radios<br>
Array Signal Processing<br>
Image/Video & Speech/Audio Processing<br>
Wireless Communication<br>
Next Generation Networks<br>
Biomedical Systems/Biological Networks<br>
RF/Microwaves/Antennas<br>
Optical Communications<br>
Adhoc and Sensor networks<br>
Smart Grids and Green Technology<br>
DSP Algorithms and Architecture<br>
VLSI and Embedded Systems</p>
</td>
<td>
<font style="margin-left:300;font-size:14px"><b>Contact Number:<br>
Dr. C. Gnana Kousalya - 9840009247</font></b>
</td>
</tr>
<tr>
<td>
<h3 style="margin-left:40px;font-size:28px; color:#333">EEE:</h3><br>
<p style="margin-left:40px; color:black;font-size:14px;line-height:20px" >Renewable Energy Resources<br>
Power system stability and control<br>
Power quality<br>
Embedded systems<br>
Special Electrical Machines<br>
Converters and Inverters<br>
Network Harmonics<br>
Power System Design</p>
</td>
<td>
<font style="margin-left:300;font-size:14px"><b>Contact Number:<br>Dr. D. Kirubakaran - 9840009248</font></b>
</td>
</tr>
<tr>
<td>
<h3 style="font-size:28px;margin-left:40px; color:#333">MECH:</h3><br>
<p style="margin-left:40px; color:black;font-size:14px;line-height:20px" >Fluid Mechanics<br>
Recent Trends in Automobiles<br>
Fracture Mechanics<br>
Waste Management<br>
CAD/CAM/CAE<br>
Advances in Manufacturing Technology<br>
Enviroinmental Engineering & Energy Resources<br>
Quality and Reliable Engineering<br>
Reverse Engineering<br>
Dynamic Mechanical Analysis, Optimization and Control.<br>
</td><td>
<font style="margin-left:300;font-size:14px"><b>Contact Number:<br> Dr. K. Arun Vasantha Geethan - 9840009249</font></b>
</td>
</tr>
<tr>
<!-- <td>
<h3 style="margin-left:40px; color:#000">MATH:</h3><br>
<p style="margin-left:40px; color:#000" >Discrete Mathematics<br>
Language Theory<br>
Applied Statistics<br>
Fluid Mechanics</p>
</td> -->
<!-- <td>
<font style="margin-left:300"><b>Contact Number:<br>Dr.T.Kalyani - 9840009435</font></b>
</td> -->
</tr>
</table>
</div>

<!-- End Class groupBottom -->
</section><!-- /topspace whiteshadow bg-black -->
<!-- /container -->
</div>
</div>
<div>
<br><br>
<h4><strong><center>SAMPLE PAPER FORMAT</center></strong></h4>

		<center><%= link_to image_tag("download_icon.jpg"),download_doc_path %>
</center>
<h3 align="Center"><b>Organized  by </b></h3><br>
            <center><%= link_to image_tag("sjit.png",alt: "SJIT"), "http://stjosephstechnology.ac.in" %></center>
            <h3 align="center"><b>In Association with</b></h2><br><br>
            <center><%= link_to image_tag("csi.png",size: "120x120",alt: "CSI"), "http://www.csi-india.org" %><br><br><br>
            <%= link_to image_tag("ieee.jpg",size: "120x120",alt: "IEEE"), "http://ieee.org/"%><br><br><br>
            <%= link_to image_tag("rip.jpeg",size: "150x50",alt: "RIP"), "http://www.ripublication.com/"%><br><br><br>
            <h3 align="center"><b>Archieved and Indexed by</b></h2><br><br><br>
            <%= link_to image_tag("rsr.png"),"http://www.researchgate.net/" %><br><br><br>
            <%=link_to image_tag("doaj.jpg"),"http://doaj.org" %><br><br><br>
            <%=link_to image_tag("google.png"),"http://scholar.google.co.in/intl/en/scholar/about.html" %><br><br><br>
            <%= link_to image_tag("EBSCO.gif",size: "160x40"),"https://www.ebsco.com/" %><br><br><br>
            <%=link_to image_tag("scopus.jpg"),"http://www.scopus.com/",size: "120x120" %><br><br><br>
            <%=link_to image_tag("dblp-logo.png"),"http://dblp.uni-trier.de/",size: "120x120" %><br><br><br></center>

</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>



<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<%= link_to "Register", new_registration_path(resource_name) %><br />
<% end -%>


<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>